// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: orbit/v1/orbit.proto

package orbitv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrbitController_WorkerSession_FullMethodName = "/orbit.v1.OrbitController/WorkerSession"
	OrbitController_Submit_FullMethodName        = "/orbit.v1.OrbitController/Submit"
)

// OrbitControllerClient is the client API for OrbitController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrbitControllerClient interface {
	WorkerSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerSessionMessage, ControllerSessionMessage], error)
	Submit(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Assignment, error)
}

type orbitControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewOrbitControllerClient(cc grpc.ClientConnInterface) OrbitControllerClient {
	return &orbitControllerClient{cc}
}

func (c *orbitControllerClient) WorkerSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerSessionMessage, ControllerSessionMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrbitController_ServiceDesc.Streams[0], OrbitController_WorkerSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerSessionMessage, ControllerSessionMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrbitController_WorkerSessionClient = grpc.BidiStreamingClient[WorkerSessionMessage, ControllerSessionMessage]

func (c *orbitControllerClient) Submit(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Assignment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Assignment)
	err := c.cc.Invoke(ctx, OrbitController_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrbitControllerServer is the server API for OrbitController service.
// All implementations must embed UnimplementedOrbitControllerServer
// for forward compatibility.
type OrbitControllerServer interface {
	WorkerSession(grpc.BidiStreamingServer[WorkerSessionMessage, ControllerSessionMessage]) error
	Submit(context.Context, *Job) (*Assignment, error)
	mustEmbedUnimplementedOrbitControllerServer()
}

// UnimplementedOrbitControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrbitControllerServer struct{}

func (UnimplementedOrbitControllerServer) WorkerSession(grpc.BidiStreamingServer[WorkerSessionMessage, ControllerSessionMessage]) error {
	return status.Errorf(codes.Unimplemented, "method WorkerSession not implemented")
}
func (UnimplementedOrbitControllerServer) Submit(context.Context, *Job) (*Assignment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedOrbitControllerServer) mustEmbedUnimplementedOrbitControllerServer() {}
func (UnimplementedOrbitControllerServer) testEmbeddedByValue()                         {}

// UnsafeOrbitControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrbitControllerServer will
// result in compilation errors.
type UnsafeOrbitControllerServer interface {
	mustEmbedUnimplementedOrbitControllerServer()
}

func RegisterOrbitControllerServer(s grpc.ServiceRegistrar, srv OrbitControllerServer) {
	// If the following call pancis, it indicates UnimplementedOrbitControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrbitController_ServiceDesc, srv)
}

func _OrbitController_WorkerSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrbitControllerServer).WorkerSession(&grpc.GenericServerStream[WorkerSessionMessage, ControllerSessionMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrbitController_WorkerSessionServer = grpc.BidiStreamingServer[WorkerSessionMessage, ControllerSessionMessage]

func _OrbitController_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitControllerServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitController_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitControllerServer).Submit(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

// OrbitController_ServiceDesc is the grpc.ServiceDesc for OrbitController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrbitController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbit.v1.OrbitController",
	HandlerType: (*OrbitControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _OrbitController_Submit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WorkerSession",
			Handler:       _OrbitController_WorkerSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "orbit/v1/orbit.proto",
}
