// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: orbit/v1/orbit.proto

package orbitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int32                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Gpu           int32                  `protobuf:"varint,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_orbit_v1_orbit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_v1_orbit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_orbit_v1_orbit_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceRequest) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ResourceRequest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ResourceRequest) GetGpu() int32 {
	if x != nil {
		return x.Gpu
	}
	return 0
}

type Worker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Total         *ResourceRequest       `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_orbit_v1_orbit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_v1_orbit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_orbit_v1_orbit_proto_rawDescGZIP(), []int{1}
}

func (x *Worker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Worker) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Worker) GetTotal() *ResourceRequest {
	if x != nil {
		return x.Total
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Resources     *ResourceRequest       `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_orbit_v1_orbit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_v1_orbit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_orbit_v1_orbit_proto_rawDescGZIP(), []int{2}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetResources() *ResourceRequest {
	if x != nil {
		return x.Resources
	}
	return nil
}

type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Job           *Job                   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Attempt       int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_orbit_v1_orbit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_v1_orbit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_orbit_v1_orbit_proto_rawDescGZIP(), []int{3}
}

func (x *Assignment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Assignment) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *Assignment) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Assignment) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Assignment) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type Completion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *Assignment            `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completion) Reset() {
	*x = Completion{}
	mi := &file_orbit_v1_orbit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completion) ProtoMessage() {}

func (x *Completion) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_v1_orbit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completion.ProtoReflect.Descriptor instead.
func (*Completion) Descriptor() ([]byte, []int) {
	return file_orbit_v1_orbit_proto_rawDescGZIP(), []int{4}
}

func (x *Completion) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *Completion) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WorkerSessionMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerSessionMessage_Register
	//	*WorkerSessionMessage_HeartbeatSessionId
	//	*WorkerSessionMessage_Completion
	Payload       isWorkerSessionMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerSessionMessage) Reset() {
	*x = WorkerSessionMessage{}
	mi := &file_orbit_v1_orbit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerSessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerSessionMessage) ProtoMessage() {}

func (x *WorkerSessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_v1_orbit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerSessionMessage.ProtoReflect.Descriptor instead.
func (*WorkerSessionMessage) Descriptor() ([]byte, []int) {
	return file_orbit_v1_orbit_proto_rawDescGZIP(), []int{5}
}

func (x *WorkerSessionMessage) GetPayload() isWorkerSessionMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerSessionMessage) GetRegister() *Worker {
	if x != nil {
		if x, ok := x.Payload.(*WorkerSessionMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerSessionMessage) GetHeartbeatSessionId() string {
	if x != nil {
		if x, ok := x.Payload.(*WorkerSessionMessage_HeartbeatSessionId); ok {
			return x.HeartbeatSessionId
		}
	}
	return ""
}

func (x *WorkerSessionMessage) GetCompletion() *Completion {
	if x != nil {
		if x, ok := x.Payload.(*WorkerSessionMessage_Completion); ok {
			return x.Completion
		}
	}
	return nil
}

type isWorkerSessionMessage_Payload interface {
	isWorkerSessionMessage_Payload()
}

type WorkerSessionMessage_Register struct {
	Register *Worker `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerSessionMessage_HeartbeatSessionId struct {
	HeartbeatSessionId string `protobuf:"bytes,2,opt,name=heartbeat_session_id,json=heartbeatSessionId,proto3,oneof"`
}

type WorkerSessionMessage_Completion struct {
	Completion *Completion `protobuf:"bytes,3,opt,name=completion,proto3,oneof"`
}

func (*WorkerSessionMessage_Register) isWorkerSessionMessage_Payload() {}

func (*WorkerSessionMessage_HeartbeatSessionId) isWorkerSessionMessage_Payload() {}

func (*WorkerSessionMessage_Completion) isWorkerSessionMessage_Payload() {}

type ControllerSessionMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControllerSessionMessage_Assignment
	//	*ControllerSessionMessage_HeartbeatAckSessionId
	//	*ControllerSessionMessage_Error
	Payload       isControllerSessionMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerSessionMessage) Reset() {
	*x = ControllerSessionMessage{}
	mi := &file_orbit_v1_orbit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerSessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerSessionMessage) ProtoMessage() {}

func (x *ControllerSessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_v1_orbit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerSessionMessage.ProtoReflect.Descriptor instead.
func (*ControllerSessionMessage) Descriptor() ([]byte, []int) {
	return file_orbit_v1_orbit_proto_rawDescGZIP(), []int{6}
}

func (x *ControllerSessionMessage) GetPayload() isControllerSessionMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControllerSessionMessage) GetAssignment() *Assignment {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSessionMessage_Assignment); ok {
			return x.Assignment
		}
	}
	return nil
}

func (x *ControllerSessionMessage) GetHeartbeatAckSessionId() string {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSessionMessage_HeartbeatAckSessionId); ok {
			return x.HeartbeatAckSessionId
		}
	}
	return ""
}

func (x *ControllerSessionMessage) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSessionMessage_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isControllerSessionMessage_Payload interface {
	isControllerSessionMessage_Payload()
}

type ControllerSessionMessage_Assignment struct {
	Assignment *Assignment `protobuf:"bytes,1,opt,name=assignment,proto3,oneof"`
}

type ControllerSessionMessage_HeartbeatAckSessionId struct {
	HeartbeatAckSessionId string `protobuf:"bytes,2,opt,name=heartbeat_ack_session_id,json=heartbeatAckSessionId,proto3,oneof"`
}

type ControllerSessionMessage_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ControllerSessionMessage_Assignment) isControllerSessionMessage_Payload() {}

func (*ControllerSessionMessage_HeartbeatAckSessionId) isControllerSessionMessage_Payload() {}

func (*ControllerSessionMessage_Error) isControllerSessionMessage_Payload() {}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_orbit_v1_orbit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_v1_orbit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_orbit_v1_orbit_proto_rawDescGZIP(), []int{7}
}

func (x *JobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	AssignmentId  string                 `protobuf:"bytes,4,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	Attempt       int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_orbit_v1_orbit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_v1_orbit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_orbit_v1_orbit_proto_rawDescGZIP(), []int{8}
}

func (x *JobStatusResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *JobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatusResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobStatusResponse) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *JobStatusResponse) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

var File_orbit_v1_orbit_proto protoreflect.FileDescriptor

const file_orbit_v1_orbit_proto_rawDesc = "" +
	"\n" +
	"\x14orbit/v1/orbit.proto\x12\borbit.v1\"R\n" +
	"\x0fResourceRequest\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x05R\x03cpu\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x05R\bmemoryMb\x12\x10\n" +
	"\x03gpu\x18\x03 \x01(\x05R\x03gpu\"h\n" +
	"\x06Worker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12/\n" +
	"\x05total\x18\x03 \x01(\v2\x19.orbit.v1.ResourceRequestR\x05total\"N\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\tresources\x18\x02 \x01(\v2\x19.orbit.v1.ResourceRequestR\tresources\"\x93\x01\n" +
	"\n" +
	"Assignment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\x03job\x18\x02 \x01(\v2\r.orbit.v1.JobR\x03job\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\"\\\n" +
	"\n" +
	"Completion\x124\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x14.orbit.v1.AssignmentR\n" +
	"assignment\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xbd\x01\n" +
	"\x14WorkerSessionMessage\x12.\n" +
	"\bregister\x18\x01 \x01(\v2\x10.orbit.v1.WorkerH\x00R\bregister\x122\n" +
	"\x14heartbeat_session_id\x18\x02 \x01(\tH\x00R\x12heartbeatSessionId\x126\n" +
	"\n" +
	"completion\x18\x03 \x01(\v2\x14.orbit.v1.CompletionH\x00R\n" +
	"completionB\t\n" +
	"\apayload\"\xb0\x01\n" +
	"\x18ControllerSessionMessage\x126\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x14.orbit.v1.AssignmentH\x00R\n" +
	"assignment\x129\n" +
	"\x18heartbeat_ack_session_id\x18\x02 \x01(\tH\x00R\x15heartbeatAckSessionId\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\t\n" +
	"\apayload\")\n" +
	"\x10JobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xa8\x01\n" +
	"\x11JobStatusResponse\x12\x1f\n" +
	"\x03job\x18\x01 \x01(\v2\r.orbit.v1.JobR\x03job\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12#\n" +
	"\rassignment_id\x18\x04 \x01(\tR\fassignmentId\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt2\xdc\x01\n" +
	"\x0fOrbitController\x12W\n" +
	"\rWorkerSession\x12\x1e.orbit.v1.WorkerSessionMessage\x1a\".orbit.v1.ControllerSessionMessage(\x010\x01\x12-\n" +
	"\x06Submit\x12\r.orbit.v1.Job\x1a\x14.orbit.v1.Assignment\x12A\n" +
	"\x06GetJob\x12\x1a.orbit.v1.JobStatusRequest\x1a\x1b.orbit.v1.JobStatusResponseB$Z\"orbit/internal/rpc/orbitv1;orbitv1b\x06proto3"

var (
	file_orbit_v1_orbit_proto_rawDescOnce sync.Once
	file_orbit_v1_orbit_proto_rawDescData []byte
)

func file_orbit_v1_orbit_proto_rawDescGZIP() []byte {
	file_orbit_v1_orbit_proto_rawDescOnce.Do(func() {
		file_orbit_v1_orbit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orbit_v1_orbit_proto_rawDesc), len(file_orbit_v1_orbit_proto_rawDesc)))
	})
	return file_orbit_v1_orbit_proto_rawDescData
}

var file_orbit_v1_orbit_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_orbit_v1_orbit_proto_goTypes = []any{
	(*ResourceRequest)(nil),          // 0: orbit.v1.ResourceRequest
	(*Worker)(nil),                   // 1: orbit.v1.Worker
	(*Job)(nil),                      // 2: orbit.v1.Job
	(*Assignment)(nil),               // 3: orbit.v1.Assignment
	(*Completion)(nil),               // 4: orbit.v1.Completion
	(*WorkerSessionMessage)(nil),     // 5: orbit.v1.WorkerSessionMessage
	(*ControllerSessionMessage)(nil), // 6: orbit.v1.ControllerSessionMessage
	(*JobStatusRequest)(nil),         // 7: orbit.v1.JobStatusRequest
	(*JobStatusResponse)(nil),        // 8: orbit.v1.JobStatusResponse
}
var file_orbit_v1_orbit_proto_depIdxs = []int32{
	0,  // 0: orbit.v1.Worker.total:type_name -> orbit.v1.ResourceRequest
	0,  // 1: orbit.v1.Job.resources:type_name -> orbit.v1.ResourceRequest
	2,  // 2: orbit.v1.Assignment.job:type_name -> orbit.v1.Job
	3,  // 3: orbit.v1.Completion.assignment:type_name -> orbit.v1.Assignment
	1,  // 4: orbit.v1.WorkerSessionMessage.register:type_name -> orbit.v1.Worker
	4,  // 5: orbit.v1.WorkerSessionMessage.completion:type_name -> orbit.v1.Completion
	3,  // 6: orbit.v1.ControllerSessionMessage.assignment:type_name -> orbit.v1.Assignment
	2,  // 7: orbit.v1.JobStatusResponse.job:type_name -> orbit.v1.Job
	5,  // 8: orbit.v1.OrbitController.WorkerSession:input_type -> orbit.v1.WorkerSessionMessage
	2,  // 9: orbit.v1.OrbitController.Submit:input_type -> orbit.v1.Job
	7,  // 10: orbit.v1.OrbitController.GetJob:input_type -> orbit.v1.JobStatusRequest
	6,  // 11: orbit.v1.OrbitController.WorkerSession:output_type -> orbit.v1.ControllerSessionMessage
	3,  // 12: orbit.v1.OrbitController.Submit:output_type -> orbit.v1.Assignment
	8,  // 13: orbit.v1.OrbitController.GetJob:output_type -> orbit.v1.JobStatusResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_orbit_v1_orbit_proto_init() }
func file_orbit_v1_orbit_proto_init() {
	if File_orbit_v1_orbit_proto != nil {
		return
	}
	file_orbit_v1_orbit_proto_msgTypes[5].OneofWrappers = []any{
		(*WorkerSessionMessage_Register)(nil),
		(*WorkerSessionMessage_HeartbeatSessionId)(nil),
		(*WorkerSessionMessage_Completion)(nil),
	}
	file_orbit_v1_orbit_proto_msgTypes[6].OneofWrappers = []any{
		(*ControllerSessionMessage_Assignment)(nil),
		(*ControllerSessionMessage_HeartbeatAckSessionId)(nil),
		(*ControllerSessionMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orbit_v1_orbit_proto_rawDesc), len(file_orbit_v1_orbit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orbit_v1_orbit_proto_goTypes,
		DependencyIndexes: file_orbit_v1_orbit_proto_depIdxs,
		MessageInfos:      file_orbit_v1_orbit_proto_msgTypes,
	}.Build()
	File_orbit_v1_orbit_proto = out.File
	file_orbit_v1_orbit_proto_goTypes = nil
	file_orbit_v1_orbit_proto_depIdxs = nil
}
