// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: orbit/v1/orbit.proto

package orbitv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrbitController_WorkerSession_FullMethodName = "/orbit.v1.OrbitController/WorkerSession"
	OrbitController_Submit_FullMethodName        = "/orbit.v1.OrbitController/Submit"
	OrbitController_GetJob_FullMethodName        = "/orbit.v1.OrbitController/GetJob"
	OrbitController_ListJobs_FullMethodName      = "/orbit.v1.OrbitController/ListJobs"
	OrbitController_DrainWorker_FullMethodName   = "/orbit.v1.OrbitController/DrainWorker"
	OrbitController_UndrainWorker_FullMethodName = "/orbit.v1.OrbitController/UndrainWorker"
)

// OrbitControllerClient is the client API for OrbitController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrbitControllerClient interface {
	WorkerSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerSessionMessage, ControllerSessionMessage], error)
	Submit(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Assignment, error)
	GetJob(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error)
	ListJobs(ctx context.Context, in *JobListRequest, opts ...grpc.CallOption) (*JobListResponse, error)
	DrainWorker(ctx context.Context, in *WorkerStateRequest, opts ...grpc.CallOption) (*WorkerStateResponse, error)
	UndrainWorker(ctx context.Context, in *WorkerStateRequest, opts ...grpc.CallOption) (*WorkerStateResponse, error)
}

type orbitControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewOrbitControllerClient(cc grpc.ClientConnInterface) OrbitControllerClient {
	return &orbitControllerClient{cc}
}

func (c *orbitControllerClient) WorkerSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerSessionMessage, ControllerSessionMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrbitController_ServiceDesc.Streams[0], OrbitController_WorkerSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerSessionMessage, ControllerSessionMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrbitController_WorkerSessionClient = grpc.BidiStreamingClient[WorkerSessionMessage, ControllerSessionMessage]

func (c *orbitControllerClient) Submit(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Assignment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Assignment)
	err := c.cc.Invoke(ctx, OrbitController_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitControllerClient) GetJob(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatusResponse)
	err := c.cc.Invoke(ctx, OrbitController_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitControllerClient) ListJobs(ctx context.Context, in *JobListRequest, opts ...grpc.CallOption) (*JobListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobListResponse)
	err := c.cc.Invoke(ctx, OrbitController_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitControllerClient) DrainWorker(ctx context.Context, in *WorkerStateRequest, opts ...grpc.CallOption) (*WorkerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerStateResponse)
	err := c.cc.Invoke(ctx, OrbitController_DrainWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitControllerClient) UndrainWorker(ctx context.Context, in *WorkerStateRequest, opts ...grpc.CallOption) (*WorkerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerStateResponse)
	err := c.cc.Invoke(ctx, OrbitController_UndrainWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrbitControllerServer is the server API for OrbitController service.
// All implementations must embed UnimplementedOrbitControllerServer
// for forward compatibility.
type OrbitControllerServer interface {
	WorkerSession(grpc.BidiStreamingServer[WorkerSessionMessage, ControllerSessionMessage]) error
	Submit(context.Context, *Job) (*Assignment, error)
	GetJob(context.Context, *JobStatusRequest) (*JobStatusResponse, error)
	ListJobs(context.Context, *JobListRequest) (*JobListResponse, error)
	DrainWorker(context.Context, *WorkerStateRequest) (*WorkerStateResponse, error)
	UndrainWorker(context.Context, *WorkerStateRequest) (*WorkerStateResponse, error)
	mustEmbedUnimplementedOrbitControllerServer()
}

// UnimplementedOrbitControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrbitControllerServer struct{}

func (UnimplementedOrbitControllerServer) WorkerSession(grpc.BidiStreamingServer[WorkerSessionMessage, ControllerSessionMessage]) error {
	return status.Errorf(codes.Unimplemented, "method WorkerSession not implemented")
}
func (UnimplementedOrbitControllerServer) Submit(context.Context, *Job) (*Assignment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedOrbitControllerServer) GetJob(context.Context, *JobStatusRequest) (*JobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedOrbitControllerServer) ListJobs(context.Context, *JobListRequest) (*JobListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedOrbitControllerServer) DrainWorker(context.Context, *WorkerStateRequest) (*WorkerStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DrainWorker not implemented")
}
func (UnimplementedOrbitControllerServer) UndrainWorker(context.Context, *WorkerStateRequest) (*WorkerStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndrainWorker not implemented")
}
func (UnimplementedOrbitControllerServer) mustEmbedUnimplementedOrbitControllerServer() {}
func (UnimplementedOrbitControllerServer) testEmbeddedByValue()                         {}

// UnsafeOrbitControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrbitControllerServer will
// result in compilation errors.
type UnsafeOrbitControllerServer interface {
	mustEmbedUnimplementedOrbitControllerServer()
}

func RegisterOrbitControllerServer(s grpc.ServiceRegistrar, srv OrbitControllerServer) {
	// If the following call pancis, it indicates UnimplementedOrbitControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrbitController_ServiceDesc, srv)
}

func _OrbitController_WorkerSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrbitControllerServer).WorkerSession(&grpc.GenericServerStream[WorkerSessionMessage, ControllerSessionMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrbitController_WorkerSessionServer = grpc.BidiStreamingServer[WorkerSessionMessage, ControllerSessionMessage]

func _OrbitController_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitControllerServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitController_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitControllerServer).Submit(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitController_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitControllerServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitController_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitControllerServer).GetJob(ctx, req.(*JobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitController_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitControllerServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitController_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitControllerServer).ListJobs(ctx, req.(*JobListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitController_DrainWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitControllerServer).DrainWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitController_DrainWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitControllerServer).DrainWorker(ctx, req.(*WorkerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitController_UndrainWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitControllerServer).UndrainWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitController_UndrainWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitControllerServer).UndrainWorker(ctx, req.(*WorkerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrbitController_ServiceDesc is the grpc.ServiceDesc for OrbitController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrbitController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbit.v1.OrbitController",
	HandlerType: (*OrbitControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _OrbitController_Submit_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _OrbitController_GetJob_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _OrbitController_ListJobs_Handler,
		},
		{
			MethodName: "DrainWorker",
			Handler:    _OrbitController_DrainWorker_Handler,
		},
		{
			MethodName: "UndrainWorker",
			Handler:    _OrbitController_UndrainWorker_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WorkerSession",
			Handler:       _OrbitController_WorkerSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "orbit/v1/orbit.proto",
}
